-- Auto-generated SQL script to update car logo paths
-- Generated by CarLogoDownloader

USE AdventureWorks2017;
GO

-- Update logo paths for downloaded car makes
-- Using LIKE matching on CarMake to match photo filenames

UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\ABT.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%ABT%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\ACURA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%ACURA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\ALPINE.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%ALPINE%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\ALTA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%ALTA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\AMC.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%AMC%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\APOLLO.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%APOLLO%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\AUDI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%AUDI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\BENTLEY.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%BENTLEY%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\BERTONE.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%BERTONE%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\BMW.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%BMW%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\BRAMMO.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%BRAMMO%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\BUGATTI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%BUGATTI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\BUICK.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%BUICK%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\BYD.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%BYD%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\CADILLAC.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%CADILLAC%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\CANOO.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%CANOO%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\CHEVROLET.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%CHEVROLET%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\CHRYSLER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%CHRYSLER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\CITROEN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%CITROEN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\DAEWOO.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%DAEWOO%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\DAIHATSU.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%DAIHATSU%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\DAIMLER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%DAIMLER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\DATSUN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%DATSUN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\DODGE.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%DODGE%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\DONGFENG.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%DONGFENG%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\EAGLE.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%EAGLE%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\FERRARI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%FERRARI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\FIAT.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%FIAT%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\FISKER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%FISKER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\FORD.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%FORD%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\FREIGHTLINER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%FREIGHTLINER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\GEELY.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%GEELY%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\GENESIS.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%GENESIS%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\GEO.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%GEO%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\GMC.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%GMC%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\HINO.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%HINO%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\HOLDEN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%HOLDEN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\HONDA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%HONDA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\HUDSON.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%HUDSON%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\HUMMER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%HUMMER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\HYUNDAI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%HYUNDAI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\INFINITI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%INFINITI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\INTERNATIONAL.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%INTERNATIONAL%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\IRIZAR.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%IRIZAR%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\ISUZU.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%ISUZU%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\IVECO.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%IVECO%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\JAGUAR.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%JAGUAR%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\JAWA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%JAWA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\JEEP.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%JEEP%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\KARMA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%KARMA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\KENWORTH.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%KENWORTH%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\KIA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%KIA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\KOENIGSEGG.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%KOENIGSEGG%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\KTM.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%KTM%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\LAMBORGHINI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%LAMBORGHINI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\LANCIA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%LANCIA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\LEXUS.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%LEXUS%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\LINCOLN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%LINCOLN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\LORDSTOWN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%LORDSTOWN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\LOTUS.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%LOTUS%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\LUCID.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%LUCID%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MACK.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MACK%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MAHINDRA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MAHINDRA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MASERATI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MASERATI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MAYBACH.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MAYBACH%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MAZDA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MAZDA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MCLAREN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MCLAREN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MERCEDES-BENZ.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MERCEDES%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MERCURY.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MERCURY%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MERKUR.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MERKUR%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MEV.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MEV%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MINI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MINI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MITSUBISHI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MITSUBISHI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MORGAN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MORGAN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\MOSLER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%MOSLER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\NAVISTAR.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%NAVISTAR%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\NIKOLA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%NIKOLA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\NISSAN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%NISSAN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\OLDSMOBILE.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%OLDSMOBILE%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\OPEL.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%OPEL%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\PAGANI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%PAGANI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\PANOZ.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%PANOZ%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\PETERBILT.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%PETERBILT%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\PEUGEOT.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%PEUGEOT%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\PININFARINA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%PININFARINA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\PLYMOUTH.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%PLYMOUTH%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\POLESTAR.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%POLESTAR%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\PONTIAC.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%PONTIAC%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\PORSCHE.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%PORSCHE%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\PREMIER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%PREMIER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\RAM.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%RAM%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\RAMBLER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%RAMBLER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\RENAULT.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%RENAULT%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\RIMAC.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%RIMAC%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\RIVIAN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%RIVIAN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\ROLLS-ROYCE.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%ROLLS%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\ROVER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%ROVER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\RUF.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%RUF%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\SAAB.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%SAAB%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\SALEEN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%SALEEN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\SATURN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%SATURN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\SCANIA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%SCANIA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\SETRA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%SETRA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\SMART.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%SMART%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\SPYKER.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%SPYKER%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\SUBARU.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%SUBARU%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\SUZUKI.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%SUZUKI%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\TAURO.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%TAURO%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\TESLA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%TESLA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\TOYOTA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%TOYOTA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\TRIUMPH.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%TRIUMPH%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\UD.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%UD%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\ULTIMA.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%ULTIMA%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\VECTOR.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%VECTOR%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\VINFAST.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%VINFAST%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\VOLKSWAGEN.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%VOLKSWAGEN%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\VOLVO.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%VOLVO%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\WORKHORSE.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%WORKHORSE%';
UPDATE dbo.CarTypeMaster SET LogoPath = '\\server\photos\ZEEKR.png', ModifiedDate = GETUTCDATE() WHERE CarMake LIKE '%ZEEKR%';

-- Summary of updated records
SELECT
    COUNT(*) as TotalMakes,
    SUM(CASE WHEN LogoPath IS NOT NULL THEN 1 ELSE 0 END) as MakesWithLogo,
    SUM(CASE WHEN LogoPath IS NULL THEN 1 ELSE 0 END) as MakesWithoutLogo
FROM dbo.CarTypeMaster;

-- List all makes with logos
SELECT CarTypeID, CarMake, LogoPath FROM dbo.CarTypeMaster WHERE LogoPath IS NOT NULL ORDER BY CarMake;